version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "iFiz"
    groups:
      dev-dependencies:
        patterns:
          - "*"
