version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
assignees:
  - "iFiz"
groups:
  dev-dependencies:
    patterns:
      - "*eslint"
      - "*"
