name: Audit
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Audit
        run: npm audit
