name: E2E
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install
        run: npm ci
      - name: Install browsers
        run: npx playwright install --with-deps
      - name: Run E2E tests
        run: npm run e2e-tests
